spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 100
  jpa:
    hibernate:
      #      更新或者创建数据表结构
      ddl-auto: update
    #      更新数据库时输出日志到控制台
    show-sql: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
server:
 port: 8080
